### PR TITLE
Support delay on queues

### LINKED ISSUE #119: [Queue] Allow FIFO queue construct to declare delivery delay
Hi, (please do point me in the right direction if it's already possible)

is there a possibility of programatically setting the [delivery delay](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-delay-queues.html) in the serverless.yml declaration?

### PR DESCRIPTION
**Pull request by t-richard**
Would fix #119 

I've worked on this because the change is small enough. 

If you're ok to merge it, I'll write the docs.

### CODE REVIEW

**Comment by mnapoli** [comment]
Thank you!

**Comment by Senseye** [comment]
I tried to add `delay: 60` to my queue config like this:

```
constructs:
  aswesome-sqs-queue:
    type: queue
    worker:
      handler: src/handlers/awesome.handler
      delay: 60
```

Now I expect `Delivery delay` to be set in Amazon SQS; but unfortunately it remains `0 Seconds`:
image

Am I doing something wrong?

**Comment by t-richard** [comment]
@Senseye it should probably be

```
constructs:
  aswesome-sqs-queue:
    type: queue
    delay: 60
    worker:
      handler: src/handlers/awesome.handler
```

Let me know if that solves the issue.

**Comment by Senseye** [comment]
> @Senseye it should probably be
> 
> ```
> constructs:
>   aswesome-sqs-queue:
>     type: queue
>     delay: 60
>     worker:
>       handler: src/handlers/awesome.handler
> ```
> 
> Let me know if that solves the issue.

@t-richard thought so! 

Then this readme needs to be updated:
https://github.com/getlift/lift/blob/master/docs/queue.md#delivery-delay
The example there is incorrect.

Thanks Richard!

**Comment by mnapoli** [comment]
Thanks! That's fixed in e3f8f1cbb15480803bb72a48f6b3c2a8a37b13a7

**Pull request merged**
